spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/jwt
        username: postgres
        password: 
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
        database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
    security:
        jwt:
            secret-key: ZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZGRkZA==   
            expiration: 86400000 # A DAY
            refresh-token: 
                expiration: 604800000 # SEVEN DAYS     

